"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import substrait.algebra_pb2
import substrait.type_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ExternalMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LITERAL_FIELD_NUMBER: builtins.int
    TYP_FIELD_NUMBER: builtins.int
    @property
    def literal(self) -> substrait.algebra_pb2.Expression.Literal: ...
    @property
    def typ(self) -> substrait.type_pb2.Type: ...
    def __init__(
        self,
        *,
        literal: substrait.algebra_pb2.Expression.Literal | None = ...,
        typ: substrait.type_pb2.Type | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["literal", b"literal", "typ", b"typ"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["literal", b"literal", "typ", b"typ"]) -> None: ...

Global___ExternalMessage: typing_extensions.TypeAlias = ExternalMessage
