# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testprotos/testprotos.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'testprotos/testprotos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from substrait import algebra_pb2 as substrait_dot_algebra__pb2
from substrait import type_pb2 as substrait_dot_type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btestprotos/testprotos.proto\x12\ntestprotos\x1a\x17substrait/algebra.proto\x1a\x14substrait/type.proto\"m\n\x0f\x45xternalMessage\x12\x37\n\x07literal\x18\x01 \x01(\x0b\x32\x1d.substrait.Expression.LiteralR\x07literal\x12!\n\x03typ\x18\x02 \x01(\x0b\x32\x0f.substrait.TypeR\x03typb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testprotos.testprotos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTERNALMESSAGE']._serialized_start=90
  _globals['_EXTERNALMESSAGE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
